In [7]:
import requests
import numpy as np
import pandas as pd
from bs4 import BeautifulSoup
from sklearn import metrics,preprocessing,svm
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import warnings
warnings.filterwarnings('ignore')

In [8]:
test_csv = pd.read_csv('eda_data.csv')
x_train, x_test, y_train, y_test = train_test_split(test_csv.drop({'Player', 'Preferred Positions'}, axis=1), test_csv['Preferred Positions'], test_size=0.2)

In [9]:

print('Logistic Regression PROBLEMM\n')
clf = LogisticRegression()
train = clf.fit(x_train, y_train)
y_pred = train.predict(x_test)
confusion = metrics.confusion_matrix(y_test, y_pred)
acc = clf.score(x_test,y_test)
print('\nAccuracy: {:.2f}\n'.format(acc))
print('Confusion Matrix\n')
print(confusion)
print('\nClassification Report\n')
print(classification_report(y_test, y_pred, target_names=['Defensive players', 'Middle players', 'Attacking players']))

Logistic Regression PROBLEMM


Accuracy: 0.87

Confusion Matrix

[[354  18   0]
 [ 26 356  41]
 [  0  49 170]]

Classification Report

                   precision    recall  f1-score   support

Defensive players       0.93      0.95      0.94       372
   Middle players       0.84      0.84      0.84       423
Attacking players       0.81      0.78      0.79       219

         accuracy                           0.87      1014
        macro avg       0.86      0.86      0.86      1014
     weighted avg       0.87      0.87      0.87      1014



In [12]:
print('SVM PROBLEM\n\n')
clf_svm = svm.SVC(kernel='linear')
clf_svm.fit(x_train, y_train)
y_pred_svm = clf_svm.predict(x_test)
accuracy_svm = metrics.accuracy_score(y_test, y_pred_svm)
confusion = metrics.confusion_matrix(y_test, y_pred_svm)
print("Accuracy of svm:",accuracy_svm)
print('Confusion Matrix\n')
print(confusion)
print('\nClassification Report Of SVM\n')
print(classification_report(y_test, y_pred_svm, target_names=['Defensive players', 'Middle players', 'Attacking players']))

SVM PROBLEM


Accuracy of svm: 0.8747534516765286
Confusion Matrix

[[353  19   0]
 [ 23 361  39]
 [  1  45 173]]

Classification Report Of SVM

                   precision    recall  f1-score   support

Defensive players       0.94      0.95      0.94       372
   Middle players       0.85      0.85      0.85       423
Attacking players       0.82      0.79      0.80       219

         accuracy                           0.87      1014
        macro avg       0.87      0.86      0.87      1014
     weighted avg       0.87      0.87      0.87      1014



In [13]:
print('NAIVE BAYES PROBLEM\n\n')
clf_gau = GaussianNB()
clf_gau.fit(x_train, y_train)
y_pred_gau = clf_gau.predict(x_test)
y_pred_gau_train = clf_gau.predict(x_train)
accuracy_gau = metrics.accuracy_score(y_test,y_pred_gau)
confusion = metrics.confusion_matrix(y_test, y_pred_gau)
print('Accuracy on Train data= ', metrics.accuracy_score(y_true = y_train, y_pred = y_pred_gau_train))
print('Accuracy on test data= ', metrics.accuracy_score(y_true = y_test, y_pred = y_pred_gau))
print('Confusion Matrix\n')
print(confusion)
print('\nClassification Report Of SVM\n')
print(classification_report(y_test, y_pred_gau, target_names=['Defensive players', 'Middle players', 'Attacking players']))

NAIVE BAYES PROBLEM


Accuracy on Train data=  0.7677690029615005
Accuracy on test data=  0.76232741617357
Confusion Matrix

[[299  73   0]
 [ 62 281  80]
 [  0  26 193]]

Classification Report Of SVM

                   precision    recall  f1-score   support

Defensive players       0.83      0.80      0.82       372
   Middle players       0.74      0.66      0.70       423
Attacking players       0.71      0.88      0.78       219

         accuracy                           0.76      1014
        macro avg       0.76      0.78      0.77      1014
     weighted avg       0.77      0.76      0.76      1014



In [20]:
test_2_csv = pd.read_csv('eda_2_data.csv')
x_train_2, x_test_2, y_train_2, y_test_2 = train_test_split(test_2_csv.drop({'Player', 'Preferred Positions'}, axis=1), test_2_csv['Preferred Positions'], test_size=0.2)

In [21]:
print('Logistic Regression PROBLEMM\n\n')
clf = LogisticRegression()
train = clf.fit(x_train_2, y_train_2)
y_pred = train.predict(x_test_2)
confusion = metrics.confusion_matrix(y_test_2, y_pred)
acc = clf.score(x_test_2, y_test_2)
print('\nAccuracy: {:.2f}\n'.format(acc))
print('Confusion Matrix\n')
print(confusion)
print('\nClassification Report\n')
print(classification_report(y_test_2, y_pred, target_names=['Defensive players', 'Middle players', 'Attacking players']))

Logistic Regression PROBLEMM



Accuracy: 0.79

Confusion Matrix

[[301  43   1]
 [ 46 336  53]
 [  4  64 166]]

Classification Report

                   precision    recall  f1-score   support

Defensive players       0.86      0.87      0.86       345
   Middle players       0.76      0.77      0.77       435
Attacking players       0.75      0.71      0.73       234

         accuracy                           0.79      1014
        macro avg       0.79      0.78      0.79      1014
     weighted avg       0.79      0.79      0.79      1014



In [24]:
print('SVM PROBLEM\n\n')
clf_svm = svm.SVC(kernel='linear')
clf_svm.fit(x_train_2, y_train_2)
y_pred_svm = clf_svm.predict(x_test_2)
accuracy_svm = metrics.accuracy_score(y_test_2, y_pred_svm)
confusion = metrics.confusion_matrix(y_test_2, y_pred_svm)
print("Accuracy of svm:",accuracy_svm)
print('Confusion Matrix\n')
print(confusion)
print('\nClassification Report Of SVM\n')
print(classification_report(y_test_2, y_pred_svm, target_names=['Defensive players', 'Middle players', 'Attacking players']))


SVM PROBLEM


Accuracy of svm: 0.7938856015779092
Confusion Matrix

[[311  34   0]
 [ 51 336  48]
 [  6  70 158]]

Classification Report Of SVM

                   precision    recall  f1-score   support

Defensive players       0.85      0.90      0.87       345
   Middle players       0.76      0.77      0.77       435
Attacking players       0.77      0.68      0.72       234

         accuracy                           0.79      1014
        macro avg       0.79      0.78      0.79      1014
     weighted avg       0.79      0.79      0.79      1014



In [25]:
print('NAIVE BAYES PROBLEM\n\n')
clf_gau = GaussianNB()
clf_gau.fit(x_train_2, y_train_2)
y_pred_gau = clf_gau.predict(x_test_2)
y_pred_gau_train = clf_gau.predict(x_train_2)
accuracy_gau = metrics.accuracy_score(y_test_2, y_pred_gau)
confusion = metrics.confusion_matrix(y_test_2, y_pred_gau)
print('Accuracy on Train data= ', metrics.accuracy_score(y_true = y_train_2, y_pred = y_pred_gau_train))
print('Accuracy on test data= ', metrics.accuracy_score(y_true = y_test_2, y_pred = y_pred_gau))
print('Confusion Matrix\n')
print(confusion)
print('\nClassification Report Of SVM\n')
print(classification_report(y_test_2, y_pred_gau, target_names=['Defensive players', 'Middle players', 'Attacking players']))


NAIVE BAYES PROBLEM


Accuracy on Train data=  0.7110069101678184
Accuracy on test data=  0.722879684418146
Confusion Matrix

[[273  71   1]
 [ 71 264 100]
 [  0  38 196]]

Classification Report Of SVM

                   precision    recall  f1-score   support

Defensive players       0.79      0.79      0.79       345
   Middle players       0.71      0.61      0.65       435
Attacking players       0.66      0.84      0.74       234

         accuracy                           0.72      1014
        macro avg       0.72      0.75      0.73      1014
     weighted avg       0.73      0.72      0.72      1014

