In [14]:
import requests
import numpy as np
import pandas as pd
from bs4 import BeautifulSoup
from sklearn import metrics,preprocessing,svm
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import warnings
warnings.filterwarnings('ignore')

In [15]:
player_list =[]
ohad = {'Player': 'ohad', 'Overall Score': 80,
                      'Height': 183, 'Weight': 96, 'Age': 23,
                      'Preferred Foot': 0,'Ball Control': 84.0, 'Dribbling': 80.0,   # Ball_Control
                      'Marking': 40.0, 'Slide Tackle': 24.0, 'Stand Tackle': 55.0,  # Defence
                      'Aggression': 54.0, 'Reactions': 74.0, 'Attack Position': 63.0,  # Mental
                      'Interceptions': 40.0, 'Vision': 90.0, 'Composure': 76.0,
                      'Crossing': 75.0, 'Short Pass': 84.0, 'Long Pass': 70.0,  # Passing
                      'Acceleration': 61.0, 'Stamina': 82.0, 'Strength': 69.0, 'Balance': 70.0,  # Physical
                      'Sprint Speed': 80.0, 'Agility': 91.0, 'Jumping': 78.0,
                      'Heading': 70.0, 'Shot Power': 76.0, 'Finishing': 75.0, 'Long Shots': 64.0,  # Shooting
                      'Curve': 73.0 ,'Free Kick Acc': 74.0, 'Penalties': 85.0, 'Volleys': 82.0}
alon = {'Player': 'alon', 'Overall Score': 80,
                      'Height': 175, 'Weight': 65, 'Age': 25,
                      'Preferred Foot': 0 ,'Ball Control': 87.0, 'Dribbling': 84.0,   # Ball_Control
                      'Marking': 70.0, 'Slide Tackle': 50.0, 'Stand Tackle': 70.0,  # Defence
                      'Aggression': 60.0, 'Reactions': 80.0, 'Attack Position': 63.0,  # Mental
                      'Interceptions': 40.0, 'Vision': 90.0, 'Composure': 76.0,
                      'Crossing': 70.0, 'Short Pass': 84.0, 'Long Pass': 75.0,  # Passing
                      'Acceleration': 61.0, 'Stamina': 90.0, 'Strength': 80.0, 'Balance': 80.0,  # Physical
                      'Sprint Speed': 85.0, 'Agility': 91.0, 'Jumping': 80.0,
                      'Heading': 70.0, 'Shot Power': 70.0, 'Finishing': 70.0, 'Long Shots': 64.0,  # Shooting
                      'Curve': 70.0 ,'Free Kick Acc': 65.0, 'Penalties': 70.0, 'Volleys': 70.0}

player_list.append(ohad)
player_list.append(alon)

In [16]:
our_stats = pd.DataFrame(player_list)
our_stats.to_csv(r'/Users/user/PycharmProjects/DataLeNetunim/wow_effect.csv', index=False)

In [22]:
our_stats = pd.read_csv("wow_effect.csv")
our_stats

Player  Overall Score  Height  Weight  Age  Preferred Foot  Ball Control  \
0   ohad             80     183      96   23               0          84.0   
1   alon             80     175      65   25               0          87.0   

   Dribbling  Marking  Slide Tackle  ...  Agility  Jumping  Heading  \
0       80.0     40.0          24.0  ...     91.0     78.0     70.0   
1       84.0     70.0          50.0  ...     91.0     80.0     70.0   

   Shot Power  Finishing  Long Shots  Curve  Free Kick Acc  Penalties  Volleys  
0        76.0       75.0        64.0   73.0           74.0       85.0     82.0  
1        70.0       70.0        64.0   70.0           65.0       70.0     70.0  

[2 rows x 35 columns]

In [18]:
test_csv = pd.read_csv('eda_data.csv')
x_train, x_test, y_train, y_test = train_test_split(test_csv.drop({'Player', 'Preferred Positions'}, axis=1), test_csv['Preferred Positions'], test_size=0.2)

In [19]:

print('Logistic Regression PROBLEMM\n')
clf = LogisticRegression()
train = clf.fit(x_train, y_train)
y_pred = train.predict(x_test)
confusion = metrics.confusion_matrix(y_test, y_pred)
acc = clf.score(x_test,y_test)
print('\nAccuracy: {:.2f}\n'.format(acc))
print('Confusion Matrix\n')
print(confusion)
print('\nClassification Report\n')
print(classification_report(y_test, y_pred, target_names=['Defensive players', 'Middle players', 'Attacking players']))

Logistic Regression PROBLEMM


Accuracy: 0.87

Confusion Matrix

[[343  23   0]
 [ 29 377  25]
 [  0  54 163]]

Classification Report

                   precision    recall  f1-score   support

Defensive players       0.92      0.94      0.93       366
   Middle players       0.83      0.87      0.85       431
Attacking players       0.87      0.75      0.80       217

         accuracy                           0.87      1014
        macro avg       0.87      0.85      0.86      1014
     weighted avg       0.87      0.87      0.87      1014



In [23]:
clf.predict(our_stats.drop({'Player'},axis=1))

array([2, 2])